# Generated by Django 5.1.7 on 2025-05-03 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_code', models.CharField(choices=[('USD', 'US Dollar ($)'), ('EUR', 'Euro (€)'), ('GBP', 'British Pound (£)'), ('INR', 'Indian Rupee (₹)'), ('JPY', 'Japanese Yen (¥)'), ('CNY', 'Chinese Yuan (¥)'), ('AUD', 'Australian Dollar (A$)'), ('CAD', 'Canadian Dollar (C$)'), ('SGD', 'Singapore Dollar (S$)'), ('AED', 'UAE Dirham (د.إ)')], default='INR', help_text='Select the currency to use throughout the marketplace', max_length=3)),
                ('symbol_position', models.CharField(choices=[('before', 'Before amount (e.g., $100)'), ('after', 'After amount (e.g., 100$)')], default='before', help_text='Position of the currency symbol relative to the amount', max_length=6)),
                ('decimal_separator', models.CharField(default='.', help_text='Character to use as decimal separator', max_length=1)),
                ('thousand_separator', models.CharField(default=',', help_text='Character to use as thousand separator', max_length=1)),
                ('decimal_places', models.PositiveSmallIntegerField(default=2, help_text='Number of decimal places to display')),
            ],
            options={
                'verbose_name': 'Currency Settings',
                'verbose_name_plural': 'Currency Settings',
            },
        ),
    ]
