# Generated by Django 5.1.7 on 2025-03-12 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="wishlist_products",
            field=models.ManyToManyField(
                blank=True, related_name="wishlisted_by", to="products.product"
            ),
        ),
    ]
