# Generated by Django 5.1.7 on 2025-03-14 18:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
        ('products', '0003_remove_category_meta_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='is_abandoned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cart',
            name='last_activity',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='custom_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='gift_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='is_gift',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='savedforlater',
            name='collection',
            field=models.CharField(blank=True, default='default', max_length=100),
        ),
        migrations.AddField(
            model_name='savedforlater',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['user'], name='cart_cart_user_id_b645f9_idx'),
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['session_id'], name='cart_cart_session_f55f25_idx'),
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['updated_at'], name='cart_cart_updated_c46eb6_idx'),
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['is_abandoned'], name='cart_cart_is_aban_fb20a9_idx'),
        ),
        migrations.AddIndex(
            model_name='cartitem',
            index=models.Index(fields=['product'], name='cart_cartit_product_985dba_idx'),
        ),
        migrations.AddIndex(
            model_name='cartitem',
            index=models.Index(fields=['variant'], name='cart_cartit_variant_f80a7b_idx'),
        ),
        migrations.AddIndex(
            model_name='savedforlater',
            index=models.Index(fields=['user', 'collection'], name='cart_savedf_user_id_9dd2bb_idx'),
        ),
    ]
