# Generated by Django 5.1.7 on 2025-03-14 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cart_is_abandoned_cart_last_activity_cart_notes_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='cart',
            name='cart_cart_user_id_b645f9_idx',
        ),
        migrations.RemoveIndex(
            model_name='cart',
            name='cart_cart_session_f55f25_idx',
        ),
        migrations.RemoveIndex(
            model_name='cart',
            name='cart_cart_updated_c46eb6_idx',
        ),
        migrations.RemoveIndex(
            model_name='cart',
            name='cart_cart_is_aban_fb20a9_idx',
        ),
        migrations.RemoveIndex(
            model_name='cartitem',
            name='cart_cartit_product_985dba_idx',
        ),
        migrations.RemoveIndex(
            model_name='cartitem',
            name='cart_cartit_variant_f80a7b_idx',
        ),
        migrations.RemoveIndex(
            model_name='savedforlater',
            name='cart_savedf_user_id_9dd2bb_idx',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='is_abandoned',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='last_activity',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='custom_price',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='gift_message',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='is_gift',
        ),
        migrations.RemoveField(
            model_name='savedforlater',
            name='collection',
        ),
        migrations.RemoveField(
            model_name='savedforlater',
            name='notes',
        ),
    ]
