# Generated by Django 5.1.7 on 2025-05-03 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_alter_cartitem_options_alter_savedforlater_options_and_more'),
        ('orders', '0003_shippingmethod_order_shipping_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='shipping_method',
            field=models.ForeignKey(blank=True, help_text='Selected shipping method', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carts', to='orders.shippingmethod'),
        ),
    ]
