# Generated by Django 5.1.7 on 2025-05-03 11:06

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_ordertracking_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('free_shipping_threshold', models.DecimalField(decimal_places=2, default=0, help_text='Order value above which shipping is free', max_digits=10)),
                ('estimated_days_min', models.PositiveIntegerField(default=3, help_text='Minimum estimated delivery days')),
                ('estimated_days_max', models.PositiveIntegerField(default=7, help_text='Maximum estimated delivery days')),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order in which to display this method')),
            ],
            options={
                'ordering': ['display_order', 'price'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='orders.shippingmethod'),
        ),
    ]
