# Generated by Django 5.1.7 on 2025-03-13 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
