# Generated by Django 5.1.7 on 2025-05-03 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_category_meta_description_and_more'),
    ]

    operations = [
    ]
