# Generated by Django 5.1.7 on 2025-05-03 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20250503_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_digital',
            field=models.BooleanField(default=False, help_text='Whether this is a digital product (no shipping required)'),
        ),
        migrations.AddField(
            model_name='product',
            name='requires_special_shipping',
            field=models.BooleanField(default=False, help_text='Whether this product requires special shipping handling'),
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Weight in kilograms', max_digits=6),
        ),
    ]
